package font

// Code generated by typesetting-utils/generators/cache/gen.go. DO NOT EDIT.

/* Implements caches for integers key->value functions.
 *
 * The cache is a fixed-size array of 8-bit, 16-bit or 32-bit integers,
 * typically 256 elements.
 *
 * The key is split into two parts: the cache index (high bits)
 * and the rest (low bits).
 *
 * The memory layout is the following :
 * 	KEY 	= <cache bits><key bits - cache bits>
 * 	VALUE 	= <key bits - cache bits><value bits>
 * with the constraints
 *	KEY in [0, 2^key bits[
 *	VALUE in [0, 2^value bits[
 *
 * The cache index is used to index into the array. The array
 * member is an integer that is used BOTH
 * to store the low bits of the key, and the value.
 *
 * The value is stored in the least significant bits of the integer.
 * The low bits of the key are stored in the most significant bits
 * of the integer.
 *
 * A cache hit is detected by comparing the low bits of the key
 * with the high bits of the integer at the array position indexed
 * by the high bits of the key. If they match, the value is extracted
 * from the least significant bits of the integer and returned.
 * Otherwise, a cache miss is reported.
 *
 * Cache operations (storage and retrieval) involve just a few
 * arithmetic operations and a single memory access.
 */

// cache21_19_8 is a cache for integer (key, value) pairs,
// with 0 <= key < 2097152 and 0 <= value < 524288
type cache21_19_8 [1 << 8]uint32

// clear should be used as init function
func (c *cache21_19_8) clear() {
	for i := range c {
		c[i] = ^uint32(0)
	}
}

func (c *cache21_19_8) get(key uint32) (uint32, bool) {
	k := key & ((1 << 8) - 1)
	v := c[k]
	if v == ^uint32(0) || (v>>19) != uint32(key>>8) {
		return 0, false
	}
	return v & ((1 << 19) - 1), true
}

func (c *cache21_19_8) set(key uint32, value uint32) {
	if (key>>21) != 0 || (value>>19) != 0 { /* overflows */
		return
	}
	c.setUnchecked(key, value)
}

// assumes key < 2097152 and value < 524288
func (c *cache21_19_8) setUnchecked(key uint32, value uint32) {
	k := key & ((1 << 8) - 1)
	v := (uint32(key>>8) << 19) | value
	c[k] = v
}

// cache21_0_13 is a cache for integer keys,
// with 0 <= key < 2097152
type cache21_0_13 [1 << 13]uint8

// clear should be used as init function
func (c *cache21_0_13) clear() {
	for i := range c {
		c[i] = ^uint8(0)
	}
}

func (c *cache21_0_13) get(key uint32) bool {
	k := key & ((1 << 13) - 1)
	v := c[k]
	return v != ^uint8(0) && v == uint8(key>>13)
}

func (c *cache21_0_13) set(key uint32) {
	if (key >> 21) != 0 { /* overflows */
		return
	}
	c.setUnchecked(key)
}

// assumes key < 2097152
func (c *cache21_0_13) setUnchecked(key uint32) {
	k := key & ((1 << 13) - 1)
	v := uint8(key >> 13)
	c[k] = v
}
