// SPDX-License-Identifier: Unlicense OR BSD-3-Clause

package unicodedata

import "unicode"

// Code generated by typesettings-utils/generators/unicodedata/cmd/main.go DO NOT EDIT.

var Cc = unicode.Cc

var Cf = unicode.Cf

var Co = unicode.Co

var Cs = unicode.Cs

var Ll = unicode.Ll

var Lm = unicode.Lm

var Lo = unicode.Lo

var Lt = unicode.Lt

var Lu = unicode.Lu

var Mc = unicode.Mc

var Me = unicode.Me

var Mn = unicode.Mn

var Nd = unicode.Nd

var Nl = unicode.Nl

var No = unicode.No

var Pc = unicode.Pc

var Pd = unicode.Pd

var Pe = unicode.Pe

var Pf = unicode.Pf

var Pi = unicode.Pi

var Po = unicode.Po

var Ps = unicode.Ps

var Sc = unicode.Sc

var Sk = unicode.Sk

var Sm = unicode.Sm

var So = unicode.So

var Zl = unicode.Zl

var Zp = unicode.Zp

var Zs = unicode.Zs

var allCategories = [...]*unicode.RangeTable{
	Cc,
	Cf,
	Co,
	Cs,
	Ll,
	Lm,
	Lo,
	Lt,
	Lu,
	Mc,
	Me,
	Mn,
	Nd,
	Nl,
	No,
	Pc,
	Pd,
	Pe,
	Pf,
	Pi,
	Po,
	Ps,
	Sc,
	Sk,
	Sm,
	So,
	Zl,
	Zp,
	Zs,
}
