package harfbuzz

type lig struct {
	components []rune // currently with length 1 or 2
	ligature   rune
}

type arabicTableEntry struct {
	First     rune
	Ligatures []lig
}

// arabicLigatureTable exposes lam-alef ligatures
var arabicLigatureTable = [...]arabicTableEntry{
	{0xFE91, []lig{
		{[]rune{0xFEE2}, 0xFC08}, /* ARABIC LIGATURE BEH WITH MEEM ISOLATED FORM */
		{[]rune{0xFEE4}, 0xFC9F}, /* ARABIC LIGATURE BEH WITH MEEM INITIAL FORM */
		{[]rune{0xFEA0}, 0xFC9C}, /* ARABIC LIGATURE BEH WITH JEEM INITIAL FORM */
		{[]rune{0xFEA4}, 0xFC9D}, /* ARABIC LIGATURE BEH WITH HAH INITIAL FORM */
		{[]rune{0xFEA8}, 0xFC9E}, /* ARABIC LIGATURE BEH WITH KHAH INITIAL FORM */
	}},
	{0xFE92, []lig{
		{[]rune{0xFEAE}, 0xFC6A}, /* ARABIC LIGATURE BEH WITH REH FINAL FORM */
		{[]rune{0xFEE6}, 0xFC6D}, /* ARABIC LIGATURE BEH WITH NOON FINAL FORM */
		{[]rune{0xFEF2}, 0xFC6F}, /* ARABIC LIGATURE BEH WITH YEH FINAL FORM */
	}},
	{0xFE97, []lig{
		{[]rune{0xFEE2}, 0xFC0E}, /* ARABIC LIGATURE TEH WITH MEEM ISOLATED FORM */
		{[]rune{0xFEE4}, 0xFCA4}, /* ARABIC LIGATURE TEH WITH MEEM INITIAL FORM */
		{[]rune{0xFEA0}, 0xFCA1}, /* ARABIC LIGATURE TEH WITH JEEM INITIAL FORM */
		{[]rune{0xFEA4}, 0xFCA2}, /* ARABIC LIGATURE TEH WITH HAH INITIAL FORM */
		{[]rune{0xFEA8}, 0xFCA3}, /* ARABIC LIGATURE TEH WITH KHAH INITIAL FORM */
	}},
	{0xFE98, []lig{
		{[]rune{0xFEAE}, 0xFC70}, /* ARABIC LIGATURE TEH WITH REH FINAL FORM */
		{[]rune{0xFEE6}, 0xFC73}, /* ARABIC LIGATURE TEH WITH NOON FINAL FORM */
		{[]rune{0xFEF2}, 0xFC75}, /* ARABIC LIGATURE TEH WITH YEH FINAL FORM */
	}},
	{0xFE9B, []lig{
		{[]rune{0xFEE2}, 0xFC12}, /* ARABIC LIGATURE THEH WITH MEEM ISOLATED FORM */
	}},
	{0xFE9F, []lig{
		{[]rune{0xFEE4}, 0xFCA8}, /* ARABIC LIGATURE JEEM WITH MEEM INITIAL FORM */
	}},
	{0xFEA3, []lig{
		{[]rune{0xFEE4}, 0xFCAA}, /* ARABIC LIGATURE HAH WITH MEEM INITIAL FORM */
	}},
	{0xFEA7, []lig{
		{[]rune{0xFEE4}, 0xFCAC}, /* ARABIC LIGATURE KHAH WITH MEEM INITIAL FORM */
	}},
	{0xFEB3, []lig{
		{[]rune{0xFEE4}, 0xFCB0}, /* ARABIC LIGATURE SEEN WITH MEEM INITIAL FORM */
	}},
	{0xFEB7, []lig{
		{[]rune{0xFEE4}, 0xFD30}, /* ARABIC LIGATURE SHEEN WITH MEEM INITIAL FORM */
	}},
	{0xFED3, []lig{
		{[]rune{0xFEF2}, 0xFC32}, /* ARABIC LIGATURE FEH WITH YEH ISOLATED FORM */
	}},
	{0xFEDF, []lig{
		{[]rune{0xFE9E}, 0xFC3F}, /* ARABIC LIGATURE LAM WITH JEEM ISOLATED FORM */
		{[]rune{0xFEA0}, 0xFCC9}, /* ARABIC LIGATURE LAM WITH JEEM INITIAL FORM */
		{[]rune{0xFEA2}, 0xFC40}, /* ARABIC LIGATURE LAM WITH HAH ISOLATED FORM */
		{[]rune{0xFEA4}, 0xFCCA}, /* ARABIC LIGATURE LAM WITH HAH INITIAL FORM */
		{[]rune{0xFEA6}, 0xFC41}, /* ARABIC LIGATURE LAM WITH KHAH ISOLATED FORM */
		{[]rune{0xFEA8}, 0xFCCB}, /* ARABIC LIGATURE LAM WITH KHAH INITIAL FORM */
		{[]rune{0xFEE2}, 0xFC42}, /* ARABIC LIGATURE LAM WITH MEEM ISOLATED FORM */
		{[]rune{0xFEE4}, 0xFCCC}, /* ARABIC LIGATURE LAM WITH MEEM INITIAL FORM */
		{[]rune{0xFEF2}, 0xFC44}, /* ARABIC LIGATURE LAM WITH YEH ISOLATED FORM */
		{[]rune{0xFEEC}, 0xFCCD}, /* ARABIC LIGATURE LAM WITH HEH INITIAL FORM */
		{[]rune{0xFE82}, 0xFEF5}, /* ARABIC LIGATURE LAM WITH ALEF WITH MADDA ABOVE ISOLATED FORM */
		{[]rune{0xFE84}, 0xFEF7}, /* ARABIC LIGATURE LAM WITH ALEF WITH HAMZA ABOVE ISOLATED FORM */
		{[]rune{0xFE88}, 0xFEF9}, /* ARABIC LIGATURE LAM WITH ALEF WITH HAMZA BELOW ISOLATED FORM */
		{[]rune{0xFE8E}, 0xFEFB}, /* ARABIC LIGATURE LAM WITH ALEF ISOLATED FORM */
	}},
	{0xFEE0, []lig{
		{[]rune{0xFEF0}, 0xFC86}, /* ARABIC LIGATURE LAM WITH ALEF MAKSURA FINAL FORM */
		{[]rune{0xFE82}, 0xFEF6}, /* ARABIC LIGATURE LAM WITH ALEF WITH MADDA ABOVE FINAL FORM */
		{[]rune{0xFE84}, 0xFEF8}, /* ARABIC LIGATURE LAM WITH ALEF WITH HAMZA ABOVE FINAL FORM */
		{[]rune{0xFE88}, 0xFEFA}, /* ARABIC LIGATURE LAM WITH ALEF WITH HAMZA BELOW FINAL FORM */
		{[]rune{0xFE8E}, 0xFEFC}, /* ARABIC LIGATURE LAM WITH ALEF FINAL FORM */
	}},
	{0xFEE3, []lig{
		{[]rune{0xFEA0}, 0xFCCE}, /* ARABIC LIGATURE MEEM WITH JEEM INITIAL FORM */
		{[]rune{0xFEA4}, 0xFCCF}, /* ARABIC LIGATURE MEEM WITH HAH INITIAL FORM */
		{[]rune{0xFEA8}, 0xFCD0}, /* ARABIC LIGATURE MEEM WITH KHAH INITIAL FORM */
		{[]rune{0xFEE4}, 0xFCD1}, /* ARABIC LIGATURE MEEM WITH MEEM INITIAL FORM */
	}},
	{0xFEE7, []lig{
		{[]rune{0xFEE2}, 0xFC4E}, /* ARABIC LIGATURE NOON WITH MEEM ISOLATED FORM */
		{[]rune{0xFEE4}, 0xFCD5}, /* ARABIC LIGATURE NOON WITH MEEM INITIAL FORM */
		{[]rune{0xFEA0}, 0xFCD2}, /* ARABIC LIGATURE NOON WITH JEEM INITIAL FORM */
		{[]rune{0xFEA4}, 0xFCD3}, /* ARABIC LIGATURE NOON WITH HAH INITIAL FORM */
	}},
	{0xFEE8, []lig{
		{[]rune{0xFEF2}, 0xFC8F}, /* ARABIC LIGATURE NOON WITH YEH FINAL FORM */
	}},
	{0xFEF3, []lig{
		{[]rune{0xFEA0}, 0xFCDA}, /* ARABIC LIGATURE YEH WITH JEEM INITIAL FORM */
		{[]rune{0xFEA4}, 0xFCDB}, /* ARABIC LIGATURE YEH WITH HAH INITIAL FORM */
		{[]rune{0xFEA8}, 0xFCDC}, /* ARABIC LIGATURE YEH WITH KHAH INITIAL FORM */
		{[]rune{0xFEE4}, 0xFCDD}, /* ARABIC LIGATURE YEH WITH MEEM INITIAL FORM */
	}},
	{0xFEF4, []lig{
		{[]rune{0xFEAE}, 0xFC91}, /* ARABIC LIGATURE YEH WITH REH FINAL FORM */
		{[]rune{0xFEE6}, 0xFC94}, /* ARABIC LIGATURE YEH WITH NOON FINAL FORM */
	}},
}

var arabicLigatureMarkTable = [...]arabicTableEntry{
	{0x0651, []lig{
		{[]rune{0x064C}, 0xFC5E}, /* ARABIC LIGATURE SHADDA WITH DAMMATAN ISOLATED FORM */
		{[]rune{0x064E}, 0xFC60}, /* ARABIC LIGATURE SHADDA WITH FATHA ISOLATED FORM */
		{[]rune{0x064F}, 0xFC61}, /* ARABIC LIGATURE SHADDA WITH DAMMA ISOLATED FORM */
		{[]rune{0x0650}, 0xFC62}, /* ARABIC LIGATURE SHADDA WITH KASRA ISOLATED FORM */
		{[]rune{0x064B}, 0xF2EE}, /* PUA ARABIC LIGATURE SHADDA WITH FATHATAN ISOLATED FORM */
	}},
}

var arabicLigature3Table = [...]arabicTableEntry{
	{0xFEDF, []lig{
		{[]rune{0xFEE4, 0xFEA4}, 0xFD88}, /* ARABIC LIGATURE LAM WITH MEEM WITH HAH INITIAL FORM */
		{[]rune{0xFEE0, 0xFEEA}, 0xF201}, /* PUA ARABIC LIGATURE LELLAH ISOLATED FORM */
		{[]rune{0xFEE4, 0xFEA0}, 0xF211}, /* PUA ARABIC LIGATURE LAM WITH MEEM WITH JEEM INITIAL FORM */
	}},
}
