name: Static Analysis
on: [push, pull_request]
permissions:
  contents: read

jobs:
  static_analysis:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
      with:
        persist-credentials: false
    - uses: WillAbides/setup-go-faster@v1.13.0
      with:
        go-version: '1.21.x'

    - name: Install analysis tools
      run: go install honnef.co/go/tools/cmd/staticcheck@v0.4.6

    - name: Vet
      run: go vet ./...

    - name: Staticcheck
      run: staticcheck ./...
